// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Header row for a Claude conversation (tied to a session).
 */
export type AiConversation = { id: string, sessionId: string, title: string | null, model: string, 
/**
 * Provider this conversation talks to (e.g. "anthropic", "groq"). Stored so
 * a restored conversation routes to the right API without re-inferring it
 * from the (ambiguous) model id. Legacy rows default to "anthropic".
 */
provider: string, createdAt: bigint, };
