// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Header row for a Claude conversation (tied to a session).
 */
export type AiConversation = { id: string, session_id: string, title: string | null, model: string, created_at: bigint, };
