// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single AI exchange (one role-tagged message).
 */
export type AiExchange = { id: string, conversation_id: string, role: string, content_json: string, input_tokens: bigint | null, output_tokens: bigint | null, created_at: bigint, sequence: bigint, };
