// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single AI exchange (one role-tagged message).
 */
export type AiExchange = { id: string, conversationId: string, role: string, contentJson: string, inputTokens: bigint | null, outputTokens: bigint | null, createdAt: bigint, sequence: bigint, };
