// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockKind } from "./BlockKind";

/**
 * A persisted block row.
 */
export type Block = { id: string, sessionId: string, ptyId: string | null, kind: BlockKind, content: string, 
/**
 * Raw ANSI bytes (escape sequences kept verbatim) – optional, can be
 * hefty so callers often skip it.
 */
ansiRaw: Array<number> | null, exitCode: number | null, durationMs: bigint | null, createdAt: bigint, sequence: bigint, };
