// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind discriminator for a block, mirroring the `kind` TEXT column.
 */
export type BlockKind = "command" | "output" | "ai_user" | "ai_assistant" | "system";
