// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageSource } from "./ImageSource";

/**
 * A persisted image record. Binary payload lives on disk at `path`.
 */
export type Image = { 
/**
 * `img_xxxxxxxxxxxx` – also surfaced inline in the terminal as a badge.
 */
id: string, sha256: string, path: string, mime: string, width: bigint, height: bigint, bytes: bigint, source: ImageSource, ocr_text: string | null, created_at: bigint, };
