// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Image-OCR search hit.
 */
export type ImageSearchHit = { image_id: string, snippet: string, rank: number, };
