// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an image originated from.
 */
export type ImageSource = "clipboard" | "screenshot" | "drop" | "terminal";
