// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One hit returned by [`search_blocks`].
 */
export type SearchHit = { 
/**
 * `blocks.id` of the matching row.
 */
block_id: string, 
/**
 * `blocks.session_id` of the matching row.
 */
session_id: string, 
/**
 * HTML snippet with `<mark>…</mark>` wrappers around matched terms.
 */
snippet: string, 
/**
 * FTS5 `bm25` score (lower = better match).
 */
rank: number, };
