// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A persisted session row.
 */
export type Session = { 
/**
 * `sess_xxxxxxxxxxxx` – stable, URL-safe.
 */
id: string, 
/**
 * User-visible title (defaults to the shell name on creation).
 */
name: string, 
/**
 * Milliseconds since UNIX epoch.
 */
createdAt: bigint, 
/**
 * Updated on every `touch` / structural mutation.
 */
updatedAt: bigint, 
/**
 * Arbitrary opaque JSON for UI metadata (icon, color, …).
 */
metadataJson: string | null, };
